# Generated by Django 3.2.4 on 2021-06-08 07:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
    ]
