# Generated by Django 3.2.4 on 2021-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stop_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
        migrations.AddField(
            model_name='route',
            name='usid',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='stop',
            name='usid',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
